# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  es2021: true
  node: true
extends: 
  - 'airbnb-base'
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
rules:
  no-console: off
  import/extensions: off
